tap/space-consistency

diff --git a/btrfs-snap b/btrfs-snap
--- a/btrfs-snap
+++ b/btrfs-snap
@@ -87,51 +87,51 @@ time_delim=":"
 ONE_OF_b_B_d_GIVEN=false
 time_duration=0
 while getopts "hVrb:d:B:ct:" arg; do
-        case "${arg}" in
-                h )
-                        echo "$SYNOPSIS"
-                        exit 0
-                        ;;
-                r )
-                        readonly="-r"
-                        ;;
-				t )
-						time_duration=$((0+$OPTARG))
-						;;
-                b )
-                        base=$OPTARG
-						if $ONE_OF_b_B_d_GIVEN; then echo "Error: the switches -b -B -d are mutually exclusive."; exit 1; fi
-						ONE_OF_b_B_d_GIVEN=true
-                        ;;
-				B )
-                        full_base=$OPTARG
-						if $ONE_OF_b_B_d_GIVEN; then echo "Error: the switches -b -B -d are mutually exclusive."; exit 1; fi
-						ONE_OF_b_B_d_GIVEN=true
-                        ;;
-                d )
-                        dir=$OPTARG
-						if $ONE_OF_b_B_d_GIVEN; then echo "Error: the switches -b -B -d are mutually exclusive."; exit 1; fi
-						ONE_OF_b_B_d_GIVEN=true
-                        ;;
-                V )
-                        echo "${prog} Version ${VERSION}"
-                        exit 0
-                        ;;
-                c )
-                        time_delim="-"
-                        ;;
-                * )
-                        echo "$USAGE"
-                        exit 1
-                        ;;
-        esac
+	case "${arg}" in
+		h )
+			echo "$SYNOPSIS"
+			exit 0
+			;;
+		r )
+			readonly="-r"
+			;;
+		t )
+			time_duration=$((0+$OPTARG))
+			;;
+		b )
+			base=$OPTARG
+			if $ONE_OF_b_B_d_GIVEN; then echo "Error: the switches -b -B -d are mutually exclusive."; exit 1; fi
+			ONE_OF_b_B_d_GIVEN=true
+			;;
+		B )
+			full_base=$OPTARG
+			if $ONE_OF_b_B_d_GIVEN; then echo "Error: the switches -b -B -d are mutually exclusive."; exit 1; fi
+			ONE_OF_b_B_d_GIVEN=true
+			;;
+		d )
+			dir=$OPTARG
+			if $ONE_OF_b_B_d_GIVEN; then echo "Error: the switches -b -B -d are mutually exclusive."; exit 1; fi
+			ONE_OF_b_B_d_GIVEN=true
+			;;
+		V )
+			echo "${prog} Version ${VERSION}"
+			exit 0
+			;;
+		c )
+			time_delim="-"
+			;;
+		* )
+			echo "$USAGE"
+			exit 1
+			;;
+	esac
 done
 
 shift $((OPTIND-1))
 
 if [ $# -ne 3 ] ; then
-        echo "$USAGE"
-        exit 1
+	echo "$USAGE"
+	exit 1
 fi
 
 # Remove trailing slash
@@ -140,31 +140,31 @@ pf=$2
 cnt=$(( $3+1 ))
 
 function log.info() {
-        logger -p ${LOG_FACILITY}.info -t ${prog} "$1"
-		echo "$1"
+	logger -p ${LOG_FACILITY}.info -t ${prog} "$1"
+	echo "$1"
 }
 
 function log.error() {
-        logger -p ${LOG_FACILITY}.err -t ${prog} "$1"
-		echo "ERROR: $1"
-		exit 1;
+	logger -p ${LOG_FACILITY}.err -t ${prog} "$1"
+	echo "ERROR: $1"
+	exit 1;
 }
 
 # Verify that the path is either a valid btrfs mountpoint
 mount -t btrfs | cut -d " " -f 3 | grep "^${mp}$" > /dev/null
 if [ $? -ne 0 ] ; then
-        # or a valid snapshot matching mp
-        btrfs subvolume show $mp | grep "${mp}$" > /dev/null
-        if [ $? -ne 0 ] ; then
-				log.error "${mp} is not a btrfs mountpoint (or old version of btrfs-tools, try > 0.19)"
-				exit 1;
-        fi
+	# or a valid snapshot matching mp
+	btrfs subvolume show $mp | grep "${mp}$" > /dev/null
+	if [ $? -ne 0 ] ; then
+		log.error "${mp} is not a btrfs mountpoint (or old version of btrfs-tools, try > 0.19)"
+		exit 1;
+	fi
 fi
 
 # set default for dir
 if [ "x$dir" == "x" ]
 then
-        dir=".snapshot"
+	dir=".snapshot"
 fi
 
 if [ "x$base" == "x" ]
@@ -177,17 +177,17 @@ if [ "x$full_base" != "x" ]; then
 	base=$full_base
 fi
 if [ ! -d $base ]; then
-		log.info "Creating $base"
-        mkdir -p $base
+	log.info "Creating $base"
+	mkdir -p $base
 fi
 base=$(readlink -f $base)
 
 if [ ${pf} == VFS ]; then
-	    snapname=$(TZ=GMT date +@GMT-%Y.%m.%d-%H.%M.%S)
-        snappattern="$@GMT-????.??.??-??.??.??"
+    snapname=$(TZ=GMT date +@GMT-%Y.%m.%d-%H.%M.%S)
+	snappattern="$@GMT-????.??.??-??.??.??"
 else
-        snapname=${pf}_$(date +%Y-%m-%d_%H${time_delim}%M${time_delim}%S)
-        snappattern="${pf}_????-??-??_??${time_delim}??${time_delim}??"
+	snapname=${pf}_$(date +%Y-%m-%d_%H${time_delim}%M${time_delim}%S)
+	snappattern="${pf}_????-??-??_??${time_delim}??${time_delim}??"
 fi
 if [ -e ${base}/${snapname} ]; then
 	log.error "cannot create snapshot in ${base}/${snapname} since a folder/file with that name already exists"
@@ -214,18 +214,18 @@ fi
 
 out=`btrfs subvol snapshot ${readonly} ${mp} ${base}/${snapname} 2>&1`
 if [ $? -eq 0 ] ; then
-		log.info "${out}"
+	log.info "${out}"
 else
-		log.error "${out}"
-		exit 1;
+	log.error "${out}"
+	exit 1;
 fi
 
 ls -dr $base/${snappattern} | tail -n +${cnt} | while read snap ; do
 	out=`btrfs subvolume delete ${snap} 2>&1`
-if [ $? -eq 0 ] ; then
-	log.info "${out}"
-else
-	log.error "${out}"
-fi
+	if [ $? -eq 0 ] ; then
+		log.info "${out}"
+	else
+		log.error "${out}"
+	fi
 done
 
